name = "stm32_config"
description = "STM32 base config"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/wolfbiters/stm32_config"

authors = ["wolf biters"]
maintainers = ["wolf biters <the.wolf.biters@gmail.com>"]
maintainers-logins = ["wolfbiters"]

[configuration.variables]
mcu = { type = "Enum", values = ["stm32f429x"], default = "stm32f429x" }
runtime = { type = "Enum", values = ["embedded"], default = "embedded" }